# mock_users.py

mock_users = {
    "test1@workspace.com": {
        "id": "1",
        "name": "김하늘",
        "nickname": "sky.h",
        "email": "test1@workspace.com",
        "avatar_url": "http://test.avatar.com/img1.jpg",
        "display_name": "하늘",
        "department": "기획팀",
        "position": "매니저",
        "responsibility": "기획 총괄",
        "space_id": "1",
        "mobiles": ["010-1234-1111"],
        "tels": [],
        "vacation_start_time": None,
        "vacation_end_time": None,
        "work_start_time": 1625441400,
        "work_end_time": 1625473800,
        "status": "activated"
    },
    "test2@workspace.com": {
        "id": "2",
        "name": "이준호",
        "nickname": "jun.l",
        "email": "test2@workspace.com",
        "avatar_url": "http://test.avatar.com/img2.jpg",
        "display_name": "준호",
        "department": "개발팀",
        "position": "사원",
        "responsibility": "프론트엔드 개발",
        "space_id": "1",
        "mobiles": ["010-1234-2222"],
        "tels": [],
        "vacation_start_time": None,
        "vacation_end_time": None,
        "work_start_time": 1625441400,
        "work_end_time": 1625473800,
        "status": "activated"
    },
    "test3@workspace.com": {
        "id": "3",
        "name": "박지수",
        "nickname": "js.park",
        "email": "test3@workspace.com",
        "avatar_url": "http://test.avatar.com/img3.jpg",
        "display_name": "지수",
        "department": "디자인팀",
        "position": "대리",
        "responsibility": "UI/UX 디자인",
        "space_id": "1",
        "mobiles": ["010-1234-3333"],
        "tels": [],
        "vacation_start_time": None,
        "vacation_end_time": None,
        "work_start_time": 1625441400,
        "work_end_time": 1625473800,
        "status": "activated"
    },
    "test4@workspace.com": {
        "id": "4",
        "name": "최가온",
        "nickname": "gaon.c",
        "email": "test4@workspace.com",
        "avatar_url": "http://test.avatar.com/img4.jpg",
        "display_name": "가온",
        "department": "운영팀",
        "position": "과장",
        "responsibility": "운영 총괄",
        "space_id": "1",
        "mobiles": ["010-1234-4444"],
        "tels": [],
        "vacation_start_time": None,
        "vacation_end_time": None,
        "work_start_time": 1625441400,
        "work_end_time": 1625473800,
        "status": "activated"
    },
    "test5@workspace.com": {
        "id": "5",
        "name": "정윤호",
        "nickname": "yunho.j",
        "email": "test5@workspace.com",
        "avatar_url": "http://test.avatar.com/img5.jpg",
        "display_name": "윤호",
        "department": "CS팀",
        "position": "사원",
        "responsibility": "고객 응대",
        "space_id": "1",
        "mobiles": ["010-1234-5555"],
        "tels": [],
        "vacation_start_time": None,
        "vacation_end_time": None,
        "work_start_time": 1625441400,
        "work_end_time": 1625473800,
        "status": "activated"
    }
}
